# Generated by Django 5.1.1 on 2024-09-28 03:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectDetail",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_ts", models.DateTimeField(auto_now_add=True)),
                ("update_ts", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=512)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResourceDetail",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_ts", models.DateTimeField(auto_now_add=True)),
                ("update_ts", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=512)),
                ("skills", models.JSONField()),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskInfo",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_ts", models.DateTimeField(auto_now_add=True)),
                ("update_ts", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=512)),
                ("skills", models.JSONField()),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resources.projectdetail",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
